config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

end

app/models/item.rb
class Item < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
	has_one :wishlist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
  	@time = Time.now;
  	@filePath = 'config';
  	@files = Dir.foreach('./' + @filePath + '/');	
  end

  def goodbye
  	@files = Dir.glob('*');
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/say/goodbye.html.erb
<h1>Goodbye!!!</h1>
<p>
	It was nice having you here.
</p>
<p>
Say <%= link_to '<button type="button">Hello</button>'.html_safe, say_hello_path %> again!
</p>
</br>
<p>
<% for file in @files %>
	<li>
		File name is: <%= file %>
	</li>
<% end %>
</p>

app/views/say/hello.html.erb
<h1>Hello From Rails!!!</h1>
<p>
	It is now <%= @time %>
</p>
</br>
</p>
	<h2>
		Files in <%= @filePath %>
	</h2>
	<% for file in @files %>
		<li>
			<%= file %>
		</li>
	<% end %>	
<p>
	Time to say 
	<%= link_to '<button type="button">Goodbye</button>'.html_safe, say_goodbye_path %>
</p>